apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "synapse.opdev.io/v1alpha1",
          "kind": "Heisenbridge",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "synapse-operator",
              "app.kubernetes.io/instance": "heisenbridge-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "heisenbridge",
              "app.kubernetes.io/part-of": "synapse-operator"
            },
            "name": "heisenbridge-sample"
          },
          "spec": {
            "synapse": {
              "name": "synapse-sample"
            }
          }
        },
        {
          "apiVersion": "synapse.opdev.io/v1alpha1",
          "kind": "MautrixSignal",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "synapse-operator",
              "app.kubernetes.io/instance": "mautrixsignal-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "mautrixsignal",
              "app.kubernetes.io/part-of": "synapse-operator"
            },
            "name": "mautrixsignal-sample"
          },
          "spec": {
            "synapse": {
              "name": "synapse-sample"
            }
          }
        },
        {
          "apiVersion": "synapse.opdev.io/v1alpha1",
          "kind": "Synapse",
          "metadata": {
            "name": "synapse-sample"
          },
          "spec": {
            "createNewPostgreSQL": false,
            "homeserver": {
              "values": {
                "reportStats": true,
                "serverName": "my.matrix.host"
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.25.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: synapse-operator.v0.3.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Heisenbridge is the Schema for the heisenbridges API
      displayName: Heisenbridge
      kind: Heisenbridge
      name: heisenbridges.synapse.opdev.io
      version: v1alpha1
    - description: MautrixSignal is the Schema for the mautrixsignals API
      displayName: Mautrix Signal
      kind: MautrixSignal
      name: mautrixsignals.synapse.opdev.io
      version: v1alpha1
    - description: Synapse is the Schema for the synapses API
      displayName: Synapse
      kind: Synapse
      name: synapses.synapse.opdev.io
      version: v1alpha1
  description: Deploys and manages the lifecycle of Synapse servers and their associated
    components (bridges, databases, ...). Synapse is the reference Matrix homeserver
    implementation.
  displayName: Synapse Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - synapse.opdev.io
          resources:
          - heisenbridges
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - synapse.opdev.io
          resources:
          - heisenbridges/finalizers
          verbs:
          - update
        - apiGroups:
          - synapse.opdev.io
          resources:
          - heisenbridges/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - synapse.opdev.io
          resources:
          - mautrixsignals
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - synapse.opdev.io
          resources:
          - mautrixsignals/finalizers
          verbs:
          - update
        - apiGroups:
          - synapse.opdev.io
          resources:
          - mautrixsignals/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - synapse.opdev.io
          resources:
          - synapses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - synapse.opdev.io
          resources:
          - synapses/finalizers
          verbs:
          - update
        - apiGroups:
          - synapse.opdev.io
          resources:
          - synapses/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: synapse-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: synapse-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/opdev/synapse-operator:v0.3.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: synapse-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: synapse-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - synapse
  - matrix
  links:
  - name: Synapse Operator
    url: https://synapse-operator.domain
  maintainers:
  - email: mgoerens@redhat.com'
    name: '''Matthias Goerens'
  maturity: alpha
  provider:
    name: Opdev
  version: 0.3.0
