apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: synapse-operator
  name: synapse-operator-synapse-heisenbridge-admin-role
rules:
- apiGroups:
  - synapse.opdev.io
  resources:
  - heisenbridges
  verbs:
  - '*'
- apiGroups:
  - synapse.opdev.io
  resources:
  - heisenbridges/status
  verbs:
  - get
