# This rule is not used by the project synapse-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the synapse.opdev.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: synapse-operator
    app.kubernetes.io/managed-by: kustomize
  name: synapse-mautrixsignal-editor-role
rules:
- apiGroups:
  - synapse.opdev.io
  resources:
  - mautrixsignals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synapse.opdev.io
  resources:
  - mautrixsignals/status
  verbs:
  - get
