# permissions for end users to view heisenbridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: heisenbridge-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: synapse-operator
    app.kubernetes.io/part-of: synapse-operator
    app.kubernetes.io/managed-by: kustomize
  name: heisenbridge-viewer-role
rules:
- apiGroups:
  - synapse.opdev.io
  resources:
  - heisenbridges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - synapse.opdev.io
  resources:
  - heisenbridges/status
  verbs:
  - get
