# permissions for end users to edit mautrixsignals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mautrixsignal-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: synapse-operator
    app.kubernetes.io/part-of: synapse-operator
    app.kubernetes.io/managed-by: kustomize
  name: mautrixsignal-editor-role
rules:
- apiGroups:
  - synapse.opdev.io
  resources:
  - mautrixsignals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synapse.opdev.io
  resources:
  - mautrixsignals/status
  verbs:
  - get
