apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: synapse-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Heisenbridge is the Schema for the heisenbridges API
      displayName: Heisenbridge
      kind: Heisenbridge
      name: heisenbridges.synapse.opdev.io
      version: v1alpha1
    - description: MautrixSignal is the Schema for the mautrixsignals API
      displayName: Mautrix Signal
      kind: MautrixSignal
      name: mautrixsignals.synapse.opdev.io
      version: v1alpha1
    - description: Synapse is the Schema for the synapses API
      displayName: Synapse
      kind: Synapse
      name: synapses.synapse.opdev.io
      version: v1alpha1
  description: Deploys and manages the lifecycle of Synapse servers and their associated
    components (bridges, databases, ...). Synapse is the reference Matrix homeserver
    implementation.
  displayName: Synapse Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - synapse
  - matrix
  links:
  - name: Synapse Operator
    url: https://synapse-operator.domain
  maintainers:
  - email: mgoerens@redhat.com'
    name: '''Matthias Goerens'
  maturity: alpha
  provider:
    name: Opdev
  version: 0.0.0
