## Append samples you want in your CSV to this file as resources ##
resources:
- synapse_v1alpha1_synapse.yaml
- synapse_v1alpha1_mautrixsignal.yaml
- synapse_v1alpha1_heisenbridge.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
