apiVersion: synapse.opdev.io/v1alpha1
kind: Synapse
metadata:
  name: synapse-sample
spec:
  createNewPostgreSQL: false
  homeserver:
    values:
      serverName: my.matrix.host
      reportStats: true
