apiVersion: synapse.opdev.io/v1alpha1
kind: Heisenbridge
metadata:
  labels:
    app.kubernetes.io/name: synapse-operator
    app.kubernetes.io/managed-by: kustomize
  name: heisenbridge-sample
spec:
  synapse:
    name: synapse-sample
