apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.Name }}
  namespace: {{ .Values.Namespace }}
data:
  heisenbridge.yaml: |
    id: heisenbridge
    url: http://{{ .Values.HeisenbridgeFQDN }}:9898
    as_token: EUFqSPQusV4mXkPKbwdHyIhthELQ1Xf9S5lSEzTrrlb0uz0ZJRHhwEljT71ByObe
    hs_token: If6r2GGlsNN4MnoW3djToADNdq0JuIJ1WNM4rKHO73WuG5QvVubj1Q4JHrmQBcS6
    rate_limited: false
    sender_localpart: heisenbridge
    namespaces:
      users:
      - regex: '@irc_.*'
        exclusive: true
      aliases: []
      rooms: []

