apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.Name }}
  namespace: {{ .Values.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi