apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name }}
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- range $key, $val := .Values.Labels }}
      {{ $key }}: {{ $val }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $key, $val := .Values.Labels }}
        {{ $key }}: {{ $val }}
        {{- end }}
    spec:
      containers:
      - name: signald
        image: docker.io/signald/signald:0.23.2
        volumeMounts:
        - mountPath: /signald
          name: signald
      volumes:
      - name: signald
        persistentVolumeClaim:
          claimName: {{ .Values.Name }}