apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name }}
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- range $key, $val := .Values.Labels }}
      {{ $key }}: {{ $val }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $key, $val := .Values.Labels }}
        {{ $key }}: {{ $val }}
        {{- end }}
    spec:
      {{if .Values.Spec.IsOpenshift -}}
      serviceAccountName: {{ .Values.Name }}
      {{- end }}
      initContainers:
        - image: "matrixdotorg/synapse:v1.82.0"
          name: "synapse-generate"
          args: [ "generate" ]
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: /data-homeserver/homeserver.yaml
            - name: SYNAPSE_SERVER_NAME
              value: {{ .Values.Status.HomeserverConfiguration.ServerName }}
            - name: SYNAPSE_REPORT_STATS
              value: {{ if .Values.Status.HomeserverConfiguration.ReportStats }}"yes"{{ else }}"no"{{ end }}
          volumeMounts:
            - name: homeserver
              mountPath: /data-homeserver
            - name: data-pv
              mountPath: /data
      containers:
        - image: "matrixdotorg/synapse:v1.82.0"
          name: "synapse"
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: /data-homeserver/homeserver.yaml
          volumeMounts:
            - name: homeserver
              mountPath: /data-homeserver
            - name: data-pv
              mountPath: /data
            {{ if .Values.Status.Bridges.Heisenbridge.Enabled -}}
            - name: data-heisenbridge
              mountPath: /data-heisenbridge
            {{- end }}
            {{ if .Values.Status.Bridges.MautrixSignal.Enabled -}}
            - name: data-mautrixsignal
              mountPath: /data-mautrixsignal
            {{- end }}
          ports:
            - containerPort: 8008
      volumes:
        - name: homeserver
          configMap:
            name: {{ .Values.Name }}
        - name: data-pv
          persistentVolumeClaim:
            claimName: {{ .Values.Name }}
        {{ if .Values.Status.Bridges.Heisenbridge.Enabled -}}
        - name: data-heisenbridge
          configMap:
            name: {{ .Values.Status.Bridges.Heisenbridge.Name }}
        {{- end }}
        {{ if .Values.Status.Bridges.MautrixSignal.Enabled -}}
        - name: data-mautrixsignal
          persistentVolumeClaim:
            claimName: {{ .Values.Status.Bridges.MautrixSignal.Name }}
        {{- end }}
