apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name }}
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- range $key, $val := .Values.Labels }}
      {{ $key }}: {{ $val }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $key, $val := .Values.Labels }}
        {{ $key }}: {{ $val }}
        {{- end }}
    spec:
      {{if .Values.Spec.IsOpenshift -}}
      serviceAccountName: {{ .Values.Name }}
      {{- end }}
      initContainers:
        # Copy homeserver.yaml from read-only ConfigMap to writable PV
        # This allows manual editing of the configuration
        - image: registry.access.redhat.com/ubi8/ubi-minimal:8.10
          name: "copy-homeserver-config"
          args:
          - if [ ! -f /data/homeserver.yaml ]; then cp /data-homeserver/homeserver.yaml /data/homeserver.yaml; fi
          command:
          - bin/sh
          - -c
          volumeMounts:
            - name: homeserver
              mountPath: /data-homeserver
            - name: data-pv
              mountPath: /data
        - image: "matrixdotorg/synapse:v1.133.0"
          name: "synapse-generate"
          args: [ "generate" ]
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: /data/homeserver.yaml
            - name: SYNAPSE_SERVER_NAME
              value: {{ .Values.Status.HomeserverConfiguration.ServerName }}
            - name: SYNAPSE_REPORT_STATS
              value: {{ if .Values.Status.HomeserverConfiguration.ReportStats }}"yes"{{ else }}"no"{{ end }}
          volumeMounts:
            - name: data-pv
              mountPath: /data
        {{ if .Values.Status.Bridges.MautrixSignal.Enabled -}}
        - image: registry.access.redhat.com/ubi8/ubi-minimal:8.10
          name: "fix-mautrixsignal-permissions"
          args:
          - chmod 644 /data-mautrixsignal/registration.yaml
          command:
          - bin/sh
          - -c
          volumeMounts:
          - name: data-mautrixsignal
            mountPath: /data-mautrixsignal
        {{- end }}
      containers:
        - image: "matrixdotorg/synapse:v1.133.0"
          name: "synapse"
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: /data/homeserver.yaml
          volumeMounts:
            - name: homeserver
              mountPath: /data-homeserver
            - name: data-pv
              mountPath: /data
            {{ if .Values.Status.Bridges.Heisenbridge.Enabled -}}
            - name: data-heisenbridge
              mountPath: /data-heisenbridge
            {{- end }}
            {{ if .Values.Status.Bridges.MautrixSignal.Enabled -}}
            - name: data-mautrixsignal
              mountPath: /data-mautrixsignal
            {{- end }}
          ports:
            - containerPort: 8008
      volumes:
        - name: homeserver
          configMap:
            name: {{ .Values.Name }}
        - name: data-pv
          persistentVolumeClaim:
            claimName: {{ .Values.Name }}
        {{ if .Values.Status.Bridges.Heisenbridge.Enabled -}}
        - name: data-heisenbridge
          configMap:
            name: {{ .Values.Status.Bridges.Heisenbridge.Name }}
        {{- end }}
        {{ if .Values.Status.Bridges.MautrixSignal.Enabled -}}
        - name: data-mautrixsignal
          persistentVolumeClaim:
            claimName: {{ .Values.Status.Bridges.MautrixSignal.Name }}
        {{- end }}
